import streamlit as st
from analyzers import ImageAnalyzer, VideoAnalyzer, TextAnalyzer
from utils import format_report, load_image, load_video, cleanup_temp

# ── Page config ──────────────────────────────────────────────────────
st.set_page_config(
    page_title="AI Media Diagnostic Agent",
    page_icon="🔍",
    layout="wide",
)

st.title("AI Media Diagnostic Agent")
st.caption(
    "An educational tool that explains *why* a piece of media has been "
    "classified as AI-generated by identifying common artifacts and patterns."
)

st.divider()

# ── Tabs ─────────────────────────────────────────────────────────────
tab_image, tab_video, tab_text = st.tabs([
    "🖼️ Image Analysis",
    "🎬 Video Analysis",
    "📝 Text Analysis",
])

# ── Image Tab ────────────────────────────────────────────────────────
with tab_image:
    uploaded_image = st.file_uploader(
        "Upload an image flagged as AI-generated",
        type=["png", "jpg", "jpeg", "webp", "bmp"],
        key="image_upload",
    )

    if uploaded_image:
        col1, col2 = st.columns([1, 1])
        with col1:
            st.image(uploaded_image, caption="Uploaded Image", use_container_width=True)

        with col2:
            if st.button("Analyze Image", key="analyze_image", type="primary"):
                with st.spinner("Analyzing image for AI artifacts..."):
                    image = load_image(uploaded_image)
                    analyzer = ImageAnalyzer()
                    report = analyzer.analyze(image)
                    st.markdown(format_report(report))
            else:
                st.info("Click **Analyze Image** to start the diagnostic scan.")

# ── Video Tab ────────────────────────────────────────────────────────
with tab_video:
    uploaded_video = st.file_uploader(
        "Upload a video flagged as AI-generated",
        type=["mp4", "avi", "mov", "mkv"],
        key="video_upload",
    )

    if uploaded_video:
        st.video(uploaded_video)

        if st.button("Analyze Video", key="analyze_video", type="primary"):
            progress_bar = st.progress(0, text="Sampling video frames...")

            def update_progress(value: float):
                progress_bar.progress(
                    min(value, 1.0),
                    text=f"Analyzing frames... {value * 100:.0f}%",
                )

            video_path = load_video(uploaded_video)
            try:
                with st.spinner("Running video diagnostics..."):
                    analyzer = VideoAnalyzer()
                    report = analyzer.analyze(video_path, progress_callback=update_progress)
                progress_bar.progress(1.0, text="Analysis complete!")
                st.markdown(format_report(report))
            finally:
                cleanup_temp(video_path)
        else:
            st.info("Click **Analyze Video** to start the diagnostic scan.")

# ── Text Tab ─────────────────────────────────────────────────────────
with tab_text:
    text_input = st.text_area(
        "Paste the text flagged as AI-generated",
        height=300,
        placeholder="Paste the AI-generated text here...",
        key="text_input",
    )

    char_count = len(text_input)
    st.caption(f"{char_count} characters | {len(text_input.split())} words")

    if text_input.strip():
        if st.button("Analyze Text", key="analyze_text", type="primary"):
            with st.spinner("Analyzing text for AI patterns..."):
                analyzer = TextAnalyzer()
                report = analyzer.analyze(text_input)
                st.markdown(format_report(report))
        else:
            st.info("Click **Analyze Text** to start the diagnostic scan.")

# ── Footer ───────────────────────────────────────────────────────────
st.divider()
st.caption(
    "⚠️ This tool is for **educational purposes**. It explains common AI artifacts "
    "in media that has already been classified by an external detection system. "
    "It does not perform AI detection itself."
)
