"""SynthID watermark detection agent.

Sends the image to Gemini with a strict-JSON prompt asking for an AI/real
verdict, confidence, and SynthID/watermark presence flags. Falls back to
a sentinel result with ``is_ai = None`` when Gemini is unavailable.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from ..schemas import SynthIDResult

logger = logging.getLogger(__name__)


_SYNTHID_PROMPT = (
    "Analyze this image to determine if it was generated by AI and, if so, "
    "which generative-AI tool produced it.\n\n"
    "First, check for SynthID digital watermarks. SynthID is embedded by Google's "
    "partner organizations, so a detected SynthID watermark strongly indicates one "
    "of these sources: Google AI (Imagen, Gemini, Veo), OpenAI, Kakao, or ElevenLabs. "
    "Use the watermark to identify which partner generated the content.\n"
    "If no partner watermark is present, analyze metadata/EXIF tags and visual "
    "artifacts (inconsistencies in textures, lighting, or anatomical details) to "
    "estimate the probability that the image is AI-generated.\n\n"
    'Categorize the source into exactly one of: "Google AI", "OpenAI", "Kakao", '
    '"ElevenLabs", "Others" (AI-generated but not a known partner), or "Unknown" '
    "(source cannot be determined).\n"
    "The confidence value is the likelihood that the image is AI-generated, "
    "expressed as a decimal from 0.0 to 1.0 (e.g. 0.85 for 85%).\n\n"
    "Return the result in JSON format:\n"
    "{\n"
    '  "isAI": boolean,\n'
    '  "confidence": number,\n'
    '  "genAITool": string,\n'
    '  "reasoning": "detailed explanation",\n'
    '  "metadata": {\n'
    '    "synthIdDetected": boolean,\n'
    '    "watermarkFound": boolean\n'
    "  }\n"
    "}"
)

_ALLOWED_GEN_AI_TOOLS = {
    "Google AI",
    "OpenAI",
    "Kakao",
    "ElevenLabs",
    "Others",
    "Unknown",
}


def _coerce_gen_ai_tool(value) -> str:
    """Map Gemini's free-text source to an allowed label, defaulting to Unknown."""
    if isinstance(value, str) and value.strip() in _ALLOWED_GEN_AI_TOOLS:
        return value.strip()
    return "Unknown"

_MIME_BY_EXT = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg"}


def _coerce_bool(value, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() == "true"
    return default


class SynthIDAgent:
    """Stateless: each ``check`` call is an independent Gemini request."""

    @staticmethod
    def check(
        image_path: str | Path,
        project_id: str,
        location: str = "us-central1",
    ) -> SynthIDResult:
        if not project_id:
            return SynthIDResult(
                is_ai=None,
                reasoning="SynthID analysis unavailable (no GCP_PROJECT_ID).",
            )

        try:
            from google import genai
            from google.genai import types

            from .gemini_router import call_gemini_with_retry

            client = genai.Client(vertexai=True, project=project_id, location=location)
            with open(image_path, "rb") as f:
                image_bytes = f.read()

            ext = os.path.splitext(str(image_path))[1].lower()
            mime_type = _MIME_BY_EXT.get(ext, "image/jpeg")

            logger.info(
                "[SynthID] Analyzing image: %s (mime: %s)", image_path, mime_type
            )
            logger.info("[SynthID] Sending prompt to Gemini:\n%s", _SYNTHID_PROMPT)
            response = call_gemini_with_retry(
                client,
                model="gemini-2.5-pro",
                contents=[
                    types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
                    _SYNTHID_PROMPT,
                ],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json"
                ),
            )
            logger.info("[SynthID] Raw Gemini response:\n%s", response.text)

            raw = response.text.strip()
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
            if raw.endswith("```"):
                raw = raw[: raw.rfind("```")]
            payload = json.loads(raw.strip())
            logger.info(
                "[SynthID] Parsed JSON payload:\n%s",
                json.dumps(payload, indent=2),
            )

            metadata = payload.get("metadata", {}) or {}
            synth_id_detected = _coerce_bool(metadata.get("synthIdDetected"))
            watermark_found = _coerce_bool(metadata.get("watermarkFound"))

            # A detected watermark is positive proof of AI generation, so the
            # likelihood is certain (1.0 == 100%) regardless of what the model
            # reported. Confidence is kept on the 0.0–1.0 scale the conflict
            # agent expects.
            confidence = (
                1.0
                if (synth_id_detected or watermark_found)
                else float(payload.get("confidence", 0) or 0)
            )

            result = SynthIDResult(
                is_ai=_coerce_bool(payload.get("isAI"), default=False)
                if payload.get("isAI") is not None
                else None,
                confidence=confidence,
                reasoning=str(payload.get("reasoning", "") or ""),
                synth_id_detected=synth_id_detected,
                watermark_found=watermark_found,
                gen_ai_tool=_coerce_gen_ai_tool(payload.get("genAITool")),
            )
            logger.info(
                "[SynthID] Final SynthIDResult:\n%s",
                json.dumps(result.model_dump(), indent=2),
            )
            return result
        except Exception as e:
            logger.exception("SynthID check failed")
            return SynthIDResult(
                is_ai=None,
                reasoning=f"SynthID analysis failed: {e}",
            )
