"""SynthID watermark detection agent.

Sends the image to Gemini with a strict-JSON prompt asking for an AI/real
verdict, confidence, and SynthID/watermark presence flags. Falls back to
a sentinel result with ``is_ai = None`` when Gemini is unavailable.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from ..schemas import SynthIDResult

logger = logging.getLogger(__name__)


_SYNTHID_PROMPT = (
    "Analyze this image to determine if it was generated by AI. "
    "Specifically, look for digital watermarks like SynthID, or visual artifacts "
    "common in AI generation (e.g., inconsistencies in textures, lighting, or anatomical details).\n\n"
    "Return the result in JSON format:\n"
    "{\n"
    '  "isAI": boolean,\n'
    '  "confidence": number,\n'
    '  "reasoning": "detailed explanation",\n'
    '  "metadata": {\n'
    '    "synthIdDetected": boolean,\n'
    '    "watermarkFound": boolean\n'
    "  }\n"
    "}"
)

_MIME_BY_EXT = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg"}


def _coerce_bool(value, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() == "true"
    return default


class SynthIDAgent:
    """Stateless: each ``check`` call is an independent Gemini request."""

    @staticmethod
    def check(
        image_path: str | Path,
        project_id: str,
        location: str = "us-central1",
    ) -> SynthIDResult:
        if not project_id:
            return SynthIDResult(
                is_ai=None,
                reasoning="SynthID analysis unavailable (no GCP_PROJECT_ID).",
            )

        try:
            from google import genai
            from google.genai import types

            from .gemini_router import call_gemini_with_retry

            client = genai.Client(vertexai=True, project=project_id, location=location)
            with open(image_path, "rb") as f:
                image_bytes = f.read()

            ext = os.path.splitext(str(image_path))[1].lower()
            mime_type = _MIME_BY_EXT.get(ext, "image/jpeg")

            response = call_gemini_with_retry(
                client,
                model="gemini-2.5-pro",
                contents=[
                    types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
                    _SYNTHID_PROMPT,
                ],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json"
                ),
            )

            raw = response.text.strip()
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
            if raw.endswith("```"):
                raw = raw[: raw.rfind("```")]
            payload = json.loads(raw.strip())

            metadata = payload.get("metadata", {}) or {}
            return SynthIDResult(
                is_ai=_coerce_bool(payload.get("isAI"), default=False)
                if payload.get("isAI") is not None
                else None,
                confidence=float(payload.get("confidence", 0) or 0),
                reasoning=str(payload.get("reasoning", "") or ""),
                synth_id_detected=_coerce_bool(metadata.get("synthIdDetected")),
                watermark_found=_coerce_bool(metadata.get("watermarkFound")),
            )
        except Exception as e:
            logger.exception("SynthID check failed")
            return SynthIDResult(
                is_ai=None,
                reasoning=f"SynthID analysis failed: {e}",
            )
