import os
import json
import base64
from datetime import datetime
from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv()

app = Flask(__name__, static_folder='dist', static_url_path='')
CORS(app)  # Allow cross-origin requests
try:
    api_key = os.getenv('GEMINI_API_KEY')
    client = genai.Client(api_key=api_key)
except Exception as e:
    print(f"Warning: Could not initialize Gemini SDK at startup. Reason: {e}")
    client = None


# In-memory history for demonstration
scan_history = []

@app.route('/api/history', methods=['GET'])
def get_history():
    return jsonify(scan_history)

@app.route('/api/history', methods=['POST'])
def add_history():
    global scan_history
    data = request.json
    new_scan = {
        'id': str(int(datetime.now().timestamp() * 1000)),
        'timestamp': datetime.now().isoformat() + 'Z',
    }
    new_scan.update(data)
    scan_history.insert(0, new_scan)
    
    # Keep only last 20 scans
    if len(scan_history) > 20:
        scan_history = scan_history[:20]
        
    return jsonify(new_scan), 201

@app.route('/api/history', methods=['DELETE'])
def clear_history():
    global scan_history
    scan_history = []
    return '', 204

@app.route('/api/analyze', methods=['POST'])
def analyze_content():
    data = request.json
    base64_data = data.get('base64Data')
    mime_type = data.get('mimeType')
    file_name = data.get('fileName')
    
    if not base64_data or not mime_type:
        return jsonify({'error': 'Missing data'}), 400

    file_type = 'image' if mime_type.startswith('image/') else 'video'
    
    prompt = f"""Analyze this {file_type} to determine if it was generated by AI. 
    Specifically, look for digital watermarks like SynthID, or visual artifacts common in AI generation (e.g., inconsistencies in textures, lighting, or anatomical details).
    
    Return the result in JSON format:
    {{
      "isAI": boolean,
      "confidence": number,
      "reasoning": "detailed explanation",
      "type": "{file_type}",
      "metadata": {{
        "synthIdDetected": boolean,
        "watermarkFound": boolean
      }}
    }}"""

    if not client:
        return jsonify({'error': 'Google AI SDK is not configured properly in the backend.'}), 500

    try:
        # Decode base64 
        image_bytes = base64.b64decode(base64_data)
        
        # Prepare content parts
        parts = [
            types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
            prompt
        ]
        
        # Call Gemini API
        response = client.models.generate_content(
            model='gemini-3-flash-preview',
            contents=parts,
            config=types.GenerateContentConfig(
                response_mime_type='application/json'
            )
        )
        
        # Parse output JSON and return to frontend
        result = json.loads(response.text)
        return jsonify(result)
        
    except Exception as e:
        print(f"Analysis error: {e}")
        return jsonify({'error': str(e)}), 500

# Serve React App in Production mode
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve(path):
    if path != "" and os.path.exists(app.static_folder + '/' + path):
        return send_from_directory(app.static_folder, path)
    else:
        return send_from_directory(app.static_folder, 'index.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=3000, debug=True)
