import { Shield, Cpu, Eye, Layers, Zap, Users, Fingerprint } from 'lucide-react';

const PIPELINE_STAGES = [
  {
    icon: Eye,
    title: 'Object Classification',
    desc: 'Identifies the media type and routes the file through the correct forensic pipeline.',
  },
  {
    icon: Cpu,
    title: 'AIDE Detection',
    desc: 'Mixture-of-Experts deep learning model combining DCT frequency analysis with spatial features for AI-probability scoring.',
  },
  {
    icon: Layers,
    title: 'Low-Level Artifact Analysis',
    desc: 'OpenCV-powered noise residuals, Laplacian edge gradients, and ELA compression maps with AI commentary.',
  },
  {
    icon: Fingerprint,
    title: 'SynthID Watermark Detection',
    desc: "Google's imperceptible watermark verifier — cryptographic proof of AI-generated origin.",
  },
  {
    icon: Shield,
    title: 'Conflict Resolution',
    desc: 'Evaluates cross-signal consistency and surfaces human-in-the-loop review when detectors disagree.',
  },
  {
    icon: Zap,
    title: 'Agentic Evaluation',
    desc: 'Gemini synthesises every signal into a plain-English forensic verdict that anyone can understand.',
  },
];

export function About() {
  return (
    <div className="max-w-5xl mx-auto space-y-16 py-4">
      {/* Hero */}
      <header className="text-center space-y-4">
        <p className="font-display text-xs tracking-[0.3em] text-primary uppercase">
          About TruthLens
        </p>
        <h1 className="font-display text-4xl md:text-5xl font-bold text-fg leading-tight">
          AI-Powered Deepfake&nbsp;
          <span className="bg-gradient-to-r from-primary to-primary-hover bg-clip-text text-transparent">
            Forensic Detection
          </span>
        </h1>
        <p className="text-muted max-w-2xl mx-auto text-base leading-relaxed">
          TruthLens is a multi-agent forensic system that combines deep learning,
          classical computer-vision artifact analysis, watermark verification, and
          large-language-model reasoning to determine whether an image was created
          by a real camera or generated by AI.
        </p>
      </header>

      {/* Mission */}
      <section className="grid md:grid-cols-2 gap-8">
        <div className="rounded-card border border-border bg-card p-6 space-y-3">
          <div className="flex items-center gap-2">
            <Users className="size-5 text-primary" />
            <h2 className="font-display text-lg font-semibold text-fg">Our Mission</h2>
          </div>
          <p className="text-sm text-muted leading-relaxed">
            Empower everyday people, journalists, and digital forensics professionals
            with transparent, interpretable tools to detect AI-generated media —
            helping build trust in the digital information ecosystem.
          </p>
        </div>

        <div className="rounded-card border border-border bg-card p-6 space-y-3">
          <div className="flex items-center gap-2">
            <Shield className="size-5 text-success" />
            <h2 className="font-display text-lg font-semibold text-fg">Why It Matters</h2>
          </div>
          <p className="text-sm text-muted leading-relaxed">
            With the rapid advancement of generative AI, distinguishing real from
            synthetic media is critical. No single detection method is enough —
            TruthLens combines six complementary forensic stages to provide
            robust, explainable verdicts.
          </p>
        </div>
      </section>

      {/* Pipeline */}
      <section className="space-y-6">
        <div className="text-center">
          <p className="font-display text-xs tracking-[0.25em] text-muted uppercase">
            Forensic Pipeline
          </p>
          <h2 className="font-display text-2xl font-semibold text-fg mt-1">
            Six-Stage Detection Flow
          </h2>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {PIPELINE_STAGES.map(({ icon: Icon, title, desc }, i) => (
            <div
              key={title}
              className="group relative rounded-card border border-border bg-card/60 hover:bg-card p-5 transition-all duration-300 hover:border-primary/40 hover:shadow-[0_0_24px_rgba(99,102,241,0.08)]"
            >
              <div className="flex items-center gap-3 mb-3">
                <span className="size-8 grid place-items-center rounded-md bg-primary/10 text-primary group-hover:bg-primary/20 transition-colors">
                  <Icon className="size-4" />
                </span>
                <span className="text-xs font-mono text-muted">Stage {i + 1}</span>
              </div>
              <h3 className="font-display text-sm font-semibold text-fg mb-1">{title}</h3>
              <p className="text-xs text-muted leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Tech */}
      <section className="rounded-card border border-border bg-card/40 p-8 text-center space-y-4">
        <h2 className="font-display text-lg font-semibold text-fg">Built With</h2>
        <div className="flex flex-wrap justify-center gap-3 text-xs text-muted">
          {[
            'React 19', 'TypeScript', 'Vite', 'Tailwind CSS v4',
            'FastAPI', 'PyTorch', 'OpenCV', 'Google Gemini',
            'SHAP', 'SynthID', 'Zustand', 'TanStack Query',
          ].map((t) => (
            <span
              key={t}
              className="px-3 py-1.5 rounded-full border border-border bg-bg-elevated hover:border-primary/30 transition-colors"
            >
              {t}
            </span>
          ))}
        </div>
      </section>
    </div>
  );
}
