import { Shield, Cpu, Eye, Layers, Zap, Users, Fingerprint } from 'lucide-react';

const PIPELINE_STAGES = [
  {
    icon: Eye,
    title: 'Object Classification',
    desc: 'Identifies the media type and routes the file through the correct forensic pipeline.',
  },
  {
    icon: Cpu,
    title: 'AIDE Detection',
    desc: 'Mixture-of-Experts deep learning model combining DCT frequency analysis with spatial features for AI-probability scoring.',
  },
  {
    icon: Layers,
    title: 'Low-Level Artifact Analysis',
    desc: 'OpenCV-powered noise residuals, Laplacian edge gradients, and ELA compression maps with AI commentary.',
  },
  {
    icon: Fingerprint,
    title: 'SynthID Watermark Detection',
    desc: "Google's imperceptible watermark verifier — cryptographic proof of AI-generated origin.",
  },
  {
    icon: Shield,
    title: 'Conflict Resolution',
    desc: 'Evaluates cross-signal consistency and surfaces human-in-the-loop review when detectors disagree.',
  },
  {
    icon: Zap,
    title: 'Agentic Evaluation',
    desc: 'Gemini synthesises every signal into a plain-English forensic verdict that anyone can understand.',
  },
];

export function About() {
  return (
    <div className="max-w-5xl mx-auto space-y-16 py-4">

      {/* ── Hero ─────────────────────────────────────── */}
      <header className="text-center space-y-4">
        <p className="font-mono text-[10px] tracking-[0.3em] text-primary uppercase">
          ▸ About TruthLens
        </p>
        <h1 className="font-display text-4xl md:text-5xl font-bold text-fg leading-tight">
          AI-Powered Deepfake&nbsp;
          <span className="text-gradient-futuristic">Forensic Detection</span>
        </h1>
        <p className="text-muted max-w-2xl mx-auto text-base leading-relaxed">
          TruthLens is a multi-agent forensic system that combines deep learning,
          classical computer-vision artifact analysis, watermark verification, and
          large-language-model reasoning to determine whether an image was created
          by a real camera or generated by AI.
        </p>
      </header>

      {/* ── Mission ──────────────────────────────────── */}
      <section className="grid md:grid-cols-2 gap-6">
        {/* Our Mission */}
        <div className="relative rounded-2xl bg-slate-50 dark:bg-slate-900/50 p-6 space-y-3 overflow-hidden group transition-all duration-300 shadow-[0_0_20px_rgba(168,85,247,0.05)] hover:shadow-[0_0_35px_rgba(168,85,247,0.22)] hover:-translate-y-0.5">
          <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-purple-500/0 to-pink-500/0 group-hover:from-purple-500/5 group-hover:to-pink-500/5 transition-all duration-300 pointer-events-none" />
          <div className="relative flex items-center gap-2">
            <Users className="size-5 text-primary" />
            <h2 className="font-display text-lg font-semibold text-fg">Our Mission</h2>
          </div>
          <p className="relative text-sm text-muted leading-relaxed">
            Empower everyday people, journalists, and digital forensics professionals
            with transparent, interpretable tools to detect AI-generated media —
            helping build trust in the digital information ecosystem.
          </p>
        </div>

        {/* Why It Matters */}
        <div className="relative rounded-2xl bg-slate-50 dark:bg-slate-900/50 p-6 space-y-3 overflow-hidden group transition-all duration-300 shadow-[0_0_20px_rgba(236,72,153,0.05)] hover:shadow-[0_0_35px_rgba(236,72,153,0.20)] hover:-translate-y-0.5">
          <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-pink-500/0 to-purple-500/0 group-hover:from-pink-500/5 group-hover:to-purple-500/5 transition-all duration-300 pointer-events-none" />
          <div className="relative flex items-center gap-2">
            <Shield className="size-5 text-success" />
            <h2 className="font-display text-lg font-semibold text-fg">Why It Matters</h2>
          </div>
          <p className="relative text-sm text-muted leading-relaxed">
            With the rapid advancement of generative AI, distinguishing real from
            synthetic media is critical. No single detection method is enough —
            TruthLens combines six complementary forensic stages to provide
            robust, explainable verdicts.
          </p>
        </div>
      </section>

      {/* ── Pipeline ─────────────────────────────────── */}
      <section className="space-y-6">
        <div className="text-center">
          <p className="font-mono text-[10px] tracking-[0.25em] text-muted uppercase">
            Forensic Pipeline
          </p>
          <h2 className="font-display text-2xl font-semibold text-fg mt-1">
            Six-Stage Detection Flow
          </h2>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {PIPELINE_STAGES.map(({ icon: Icon, title, desc }, i) => (
            <div
              key={title}
              className="agent-card animate-agent-breathe group rounded-2xl bg-card/60 hover:bg-card p-5 transition-all duration-300 shadow-[0_0_15px_rgba(168,85,247,0.05)] hover:shadow-[0_0_40px_rgba(168,85,247,0.22)] hover:-translate-y-1"
              style={{ animationDelay: `${i * 0.5}s` }}
              onMouseMove={(e) => {
                const r = e.currentTarget.getBoundingClientRect();
                e.currentTarget.style.setProperty('--mx', `${((e.clientX - r.left) / r.width) * 100}%`);
                e.currentTarget.style.setProperty('--my', `${((e.clientY - r.top) / r.height) * 100}%`);
              }}
            >
              <div className="flex items-center gap-3 mb-3">
                <span className="size-8 rounded-xl grid place-items-center bg-primary/10 text-primary group-hover:bg-primary/20 group-hover:shadow-[0_0_12px_rgba(168,85,247,0.45)] transition-all">
                  <Icon className="size-4" />
                </span>
                <span className="text-xs font-mono text-muted tracking-wider">STAGE {i + 1}</span>
              </div>
              <h3 className="font-display text-sm font-semibold text-fg mb-1">{title}</h3>
              <p className="text-xs text-muted leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Tech Stack ───────────────────────────────── */}
      <section className="rounded-3xl bg-gradient-to-br from-purple-50/70 to-pink-50/70 dark:from-purple-950/20 dark:to-pink-950/20 p-8 text-center space-y-4">
        <p className="font-mono text-[10px] tracking-[0.25em] text-muted uppercase">Technology Stack</p>
        <h2 className="font-display text-lg font-semibold text-fg">Built With</h2>
        <div className="flex flex-wrap justify-center gap-2 text-xs">
          {[
            'React 19', 'TypeScript', 'Vite', 'Tailwind CSS v4',
            'FastAPI', 'PyTorch', 'OpenCV', 'Google Gemini',
            'SHAP', 'SynthID', 'Zustand', 'TanStack Query',
          ].map((t) => (
            <span
              key={t}
              className="px-4 py-1.5 rounded-full bg-white dark:bg-slate-800 shadow-sm hover:shadow-[0_0_15px_rgba(168,85,247,0.35)] font-mono text-muted hover:text-fg transition-all cursor-default"
            >
              {t}
            </span>
          ))}
        </div>
      </section>

    </div>
  );
}
